<?php
$title = $this -> translate( 'Reserve Piano Room' );
$this -> headTitle( $title );
$this -> headLink() -> appendStylesheet( '/confirm-popup/css/style.css' );
$this -> headScript() -> appendFile('/confirm-popup/js/main.js');
$this -> headScript() -> appendFile('/confirm-popup/js/modernizr.js');
?>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
	<div class="carousel-inner">
		<div class="item">
			<img src="/img/jumbotron_bg.jpg" alt="">
			<div class="container" >
                <div class="carousel-caption" style="padding-bottom: 10px;right: 15%;left: 15%;">
					<p><div id="content-0" class="b"></div></p>
				</div>
			</div>
		</div>
		<div class="item active">
			<img src="/img/jumbotron_bg.jpg" alt="">
			<div class="container">
				<div class="carousel-caption" style="padding-bottom: 10px;right: 15%;left: 15%;">
					<p><div id="content-1"></div></p>
				</div>
			</div>
		</div>
		<div class="item">
			<img src="/img/jumbotron_bg.jpg" alt="">
			<div class="container">
				<div class="carousel-caption" style="padding-bottom: 10px;right: 15%;left: 15%;">
					<p><div id="content-2"></div></p>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>


<div class="main-text text-center">
	<h1>
<?php echo $this -> translate( 'Reserve Piano Room' ); ?>    <a class="btn btn-clear btn-sm" id="print" href="#"><?php echo $this->translate('Print')?></a>
	</h1>
    <?php if($isAdmin):?>

    <?php endif;?>
    <div class="table-responsive center-block" style="margin-right: 15% !important;margin-left: 15% !important;width: 70%">
        <table class="table">
            <tr>
                <td>
                    <a class="btn btn-clear btn-sm btn-min-block btn-clicked" id="room1"><?php echo $this -> translate( 'Room 1' ); ?></a>
                </td>
                <td>
                    <a class="btn btn-clear btn-sm btn-min-block" id="room2"><?php echo $this -> translate( 'Room 2' ); ?></a>
                </td>
                <td>
                    <a class="btn btn-clear btn-sm btn-min-block" id="room3"><?php echo $this -> translate( 'Room 3' ); ?></a>
                </td>
            </tr>
        </table>
    </div>
</div>

<style>

	/* GLOBAL STYLES -------------------------------------------------- */
	/* Padding below the footer and lighter body text */

	body {
		color: #5a5a5a;
	}

	/* CUSTOMIZE THE CAROUSEL -------------------------------------------------- */

	/* Carousel base class */
	.carousel {
		height: 800px;
		margin-bottom: 0px;
	}
	/* Since positioning the image, we need to help out the caption */
	.carousel-caption {
		z-index: 10;
		border-radius: 20px;
		background: rgba(0, 0, 0, 0.55);
		box-shadow: 0px 0px 20px #333;

	}

	/* Declare heights because of positioning of img element */
	.carousel .item {
		height: 800px;
		background-color: #777;
		z-index: 0;
	}

	.carousel-inner > .item > img {
		position: absolute;
		top: 0;
		left: 0;
		min-width: 100%;
		height: 800px;
	}


	/* MARKETING CONTENT -------------------------------------------------- */

	/* Center align the text within the three columns below the carousel */
	.marketing .col-lg-4 {
		margin-bottom: 20px;
		text-align: center;
	}
	.marketing h2 {
		font-weight: normal;
	}
	.marketing .col-lg-4 p {
		margin-right: 10px;
		margin-left: 10px;
	}


	/* Featurettes ------------------------- */

	.featurette-divider {
		margin: 80px 0; /* Space out the Bootstrap <hr> more */
	}

	/* Thin out the marketing headings */
	.featurette-heading {
		font-weight: 300;
		line-height: 1;
		letter-spacing: -1px;
	}

	/* RESPONSIVE CSS -------------------------------------------------- */

	@media (min-width: 768px) {

		/* Navbar positioning foo */
		.navbar-wrapper {
			margin-top: 20px;
		}
		.navbar-wrapper .container {
			padding-right: 15px;
			padding-left: 15px;
		}
		.navbar-wrapper .navbar {
			padding-right: 0;
			padding-left: 0;
		}

		/* The navbar becomes detached from the top, so we round the corners */
		.navbar-wrapper .navbar {
			border-radius: 4px;
		}

		/* Bump up size of carousel content */
		.carousel-caption p {
			margin-bottom: 20px;
			font-size: 21px;
			line-height: 1.4;
		}

		.featurette-heading {
			font-size: 50px;
		}
	}

	@media (min-width: 992px) {
		.featurette-heading {
			margin-top: 120px;
		}
	}

	.main-text
	{
		position: absolute;
		text-align: center;
		top: 70px;
		width: 100%;
		color: #333;
		text-shadow: 0px 0px 5px rgba(100%,100%,100%,0.5);

	}
	.btn-min-block
	{
		min-width: 170px;
		line-height: 26px;
	}
	.btn-clear
	{
		color: #333;
		background-color: transparent;
		border-color: #333;
		box-shadow:0px 0px 3px rgba(100%,100%,100%,0.5);
		text-shadow: 0px 0px 3px rgba(100%,100%,100%,0.5);
		margin-right: 10px;
		margin-left: 10px;
	}
	.btn-clear:hover
	{
		color: #000;
		background-color: rgba(100%,100%,100%,0.7);
	}

	.btn-clicked{
		color: #000;
		background-color: rgba(100%,100%,100%,0.4);
	}


</style>

<script>
	var content_0 = -1;
	var content_1 = 0;
	var content_2 = 1;
	var room = 1;

	$(function() {

		// Slide load
		$("#content-0").load("<?= $this->url();?>" + "/page/" + content_0 + "/room/" + room);
		$("#content-1").load("<?= $this->url();?>" + "/page/" + content_1 + "/room/" + room);
		$("#content-2").load("<?= $this->url();?>" + "/page/" + content_2 + "/room/" + room);

		$("#myCarousel").on('slide.bs.carousel', function(e) {
			var slideFrom = $(this).find('.active').index();
			var slideTo = $(e.relatedTarget).index();
			if (slideTo === 0) {
				content_2 = content_0 - 1;
				content_1 = content_0 + 1;
				if (slideFrom !== 1)
					$("#content-1").load("<?= $this->url();?>" + "/page/" + content_1 + "/room/" + room);
				if (slideFrom !== 2)
					$("#content-2").load("<?= $this->url();?>" + "/page/" + content_2 + "/room/" + room);
			} else if (slideTo === 1) {
				content_0 = content_1 - 1;
				content_2 = content_1 + 1;
				if (slideFrom !== 0)
					$("#content-0").load("<?= $this->url();?>" + "/page/" + content_0 + "/room/" + room);
				if (slideFrom !== 2)
					$("#content-2").load("<?= $this->url();?>" + "/page/" + content_2 + "/room/" + room);
			} else {
				content_0 = content_2 + 1;
				content_1 = content_2 - 1;
				if (slideFrom !== 0)
					$("#content-0").load("<?= $this->url();?>" + "/page/" + content_0 + "/room/" + room);
				if (slideFrom !== 1)
					$("#content-1").load("<?= $this->url();?>" + "/page/" + content_1 + "/room/" + room);
			}
		});
		
		// Room Switch
		$("#room1").click(function() {
			reload(1);
		});
		$("#room2").click(function() {
			reload(2);
		});
		$("#room3").click(function() {
			reload(3);
		});
        $("#print").click(function() {			
            window.open("<?= $this->url();?>" + "/print/" + $("#myCarousel").find('.active').index() + "/room/" + room, 'print','width=500,height=500');
		});
	});
	function reload(newroom) {
		$("#room" + room).toggleClass("btn-clicked");
		room = newroom;
		$("#room" + room).toggleClass("btn-clicked");
		$("#content-0").load("<?= $this->url();?>" + "/page/" + content_0 + "/room/" + room);
		$("#content-1").load("<?= $this->url();?>" + "/page/" + content_1 + "/room/" + room);
		$("#content-2").load("<?= $this->url();?>" + "/page/" + content_2 + "/room/" + room);
	}
	function Reload() {
		reload(room);
	}
</script> 