<?php
	const CLASS_START = 0;
	const CLASS_END = 13;

$dateStringsYMD = generateDateStrings( $first, $last, 'Y-m-d' );
$dateStringsMD = generateDateStrings( $first, $last, 'm-d' );
$RecordItems = processData( $resultset, $room );
?>

<div class="table-responsive center-block table-content" style="margin-top: -20px;">	
	<div class="h3">
		<?php echo weekDescription( $page, $first, $last, $this ); ?>
	</div>
	<table class="table table-striped table-hover">
		<tr>
			<th class="text-center"><?php echo $this -> translate( 'Time \\ Date' ); ?></th>
			<?php foreach ( $dateStringsMD as $date ) : ?>
				<th class="text-center">
					<?php echo $date; ?>　
				</th>
			<?php endforeach; ?>
		</tr>

		<?php for ( $class = CLASS_START; $class <= CLASS_END; $class++ ): ?>
			<tr>
				<th class="text-center"><?php echo getClassTime( $class ) ?></th>
				<?php foreach ( $dateStringsYMD as $date ) : ?>
					<?php if ( array_key_exists( $date, $RecordItems ) && array_key_exists( $class, $RecordItems[ $date ] ) ): ?>
						<td class="text-center table-content-light" data-key="" data-display="" data-reservable="false">
							<?php foreach ( $RecordItems[ $date ][ $class ] as $record ): ?>							
								<?php echo $record[ 'displayName' ]; ?>
							<?php endforeach; ?>
						</td>
					<?php else: ?>
						<?php $data_key = sprintf( 'd/%s/c/%d/r/%d/', $date, $class, $room ); ?>
						<?php $data_display = $date . '，' . getClassTime( $class ); ?>					
						<td class="text-center table-content-light" data-key="<?php echo $data_key ?>" data-display="<?php echo $data_display; ?>" data-reservable="<?php echo $reservable; ?>">
							<span id="reserve" style="display:none"><?php echo $this -> translate( 'reserve' ); ?></span>
						</td>
					<?php endif; ?>
				<?php endforeach; ?>	
			</tr>
		<?php endfor; ?>
	</table>
</div>
<div id="dialog-confirm"></div>

<script>
	// table
	$(function() {
		$('.table-hover td').unbind().click(function() {
			var Key = $(this).attr("data-key");
			var dataDisplay = $(this).attr("data-display");
			var reservable = $(this).attr("data-reservable");
			if (reservable !== "false") {
				if (confirm('<?php echo $this -> translate( 'Confirm reservation' ); ?>' + ':' + dataDisplay)) {
					jQuery.get('/ReservePianoRoom/m/' + Key, function(data) {
						if (data === "Success"){
							Reload();
						}else if(data === "Exceed"){
							alert('Personal reserve limit exceed!');
						}else{
							alert('Something Wrong! ...' + data);
						}
					});
				}
			} else {
				//alert('<?php echo $this -> translate( 'Not able to reserve!' ); ?>');
			}
			return false;
		}).mouseover(function() {
			var reservable = $(this).attr("data-reservable");
			if (reservable === "true") {
				$(this).find('span').fadeIn(0);
			}
			return false;
		}).mouseout(function() {
			var reservable = $(this).attr("data-reservable");
			if (reservable === "true") {
				$(this).find('span').fadeOut(0);
			}
			return false;
		});
	});

</script>

<style>
	.h3{
		color: #BFBFBF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);		
	}
	.table-content{
		color: #9F9F9F;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}
	.table-content-light{
		color: #FFFFFF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}	
</style>


<?php

function generateDateStrings( $first, $last, $format ) {
	$dateStrings = array();
	for ( $date = clone $first; $date <= $last; $date -> modify( '+1 day' ) ) {
		array_push( $dateStrings, $date -> format( $format ) );
	}
	return $dateStrings;
}

function weekDescription( $page, $first, $last, $view ) {
	if ( $page == 0 ) {
		return $view -> translate( 'Current Week' );
	} elseif ( $page == 1 ) {
		return $view -> translate( 'Next Week' );
	} elseif ( $page == -1 ) {
		return $view -> translate( 'Last Week' );
	} else {
		return $first -> format( 'Y-m-d' ) . '~' . $last -> format( 'Y-m-d' );
	}
}

function processData( $resultset, $room ) {
	$current = $resultset -> current();
	$RecordItems = array();
	while ( $current ) {
		if ( $current -> room == $room ) {
			if ( !array_key_exists( $current -> date, $RecordItems ) ) {
				$RecordItems[ $current -> date ] = array();
			}
			if ( !array_key_exists( $current -> class, $RecordItems[ $current -> date ] ) ) {
				$RecordItems[ $current -> date ][ $current -> class ] = array();
			}
			$RecordItems[ $current -> date ][ $current -> class ][ $current -> room ] = array(
				'reserve_id' => $current -> reserve_id,
				'room' => $current -> room,
				'uid' => $current -> uid,
				'displayName' => $current -> userData -> getDisplayName(),
				'flag' => $current -> flag,
				'comment' => $current -> comment,
			);
		}
		$resultset -> next();
		$current = $resultset -> current();
	}
	return $RecordItems;
}

function getClassTime( $class ) {
	return sprintf( '%02d:00 ~ %02d:00', $class + 8, $class + 9 );
}
