<?php
	const CLASS_START = 0;
	const CLASS_END = 13;

$dateStringsYMD = generateDateStrings( $first, $last, 'Y-m-d' );
$dateStringsMD = generateDateStrings( $first, $last, 'm-d' );
$RecordItems = processData( $resultset, $room, $this );
?>

<div class="table-responsive center-block table-content" style="margin-top: -20px;">	
	<div class="h3">
		<?php echo weekDescription( $page, $first, $last, $this ); ?>
	</div>
	<table class="table table-striped table-hover">
		<tr>
			<th class="text-center"><?php echo $this -> translate( 'Time \\ Date' ); ?></th>
			<?php foreach ( $dateStringsMD as $date ) : ?>
				<th class="text-center">
					<?php echo $date; ?>　
				</th>
			<?php endforeach; ?>
		</tr>

		<?php for ( $class = CLASS_START; $class <= CLASS_END; $class++ ): ?>
			<tr>
				<th class="text-center"><?php echo getClassTime( $class ) ?></th>
				<?php foreach ( $dateStringsYMD as $date ) : ?>
					<?php $data_key = sprintf( 'd/%s/c/%d/r/%d/', $date, $class, $room ); ?>
					<?php $data_display = $date . '，' . getClassTime( $class ); ?>		
					<?php if ( array_key_exists( $date, $RecordItems ) && array_key_exists( $class, $RecordItems[ $date ] ) ): ?>
						<?php if ( array_key_exists( $room, $RecordItems[ $date ][ $class ] ) ): ?>	
							<?php if($RecordItems[ $date ][ $class ][ $room ][ 'uid' ] == $this -> zfcUserIdentity() -> getId()):?>
								<td class="text-center table-content-self" data-key="<?php echo $data_key ?>" data-display="<?php echo $data_display; ?>" data-reservable="false" data-self="true">
									<div><?php echo $RecordItems[ $date ][ $class ][ $room ][ 'displayName' ]; ?></div>
									<span id="reserve" class="table-content-light" style="display:none"><?php echo $this -> translate( 'cancel' ); ?></span>
								</td>
							<?php else: ?>
								<td class="text-center table-content-light" data-key="" data-display="" data-reservable="false">
									<div><?php echo $RecordItems[ $date ][ $class ][ $room ][ 'displayName' ]; ?></div>
								</td>							
							<?php endif;?>
						<?php else: ?>
							<?php $data_key = sprintf( 'd/%s/c/%d/r/%d/', $date, $class, $RecordItems[ $date ][ $class ][ 'room' ]); ?>
							<?php $data_display = $date . '，' . getClassTime( $class ); ?>									
							<td class="text-center table-content-another" data-key="<?php echo $data_key ?>" data-display="<?php echo $data_display; ?>" data-reservable="false" data-self="true">
								<div><?php echo getRoomText($RecordItems[ $date ][ $class ][ 'room' ],$this);?></div>
								<span id="reserve" class="table-content-light" style="display:none"><?php echo $this -> translate( 'cancel' ); ?></span>
							</td>
						<?php endif; ?>
					<?php else: ?>									
						<td class="text-center" data-key="<?php echo $data_key ?>" data-display="<?php echo $data_display; ?>" data-reservable="<?php echo $reservable; ?>">
							<span id="reserve" class="table-content-light" style="display:none"><?php echo $this -> translate( 'reserve' ); ?></span>
						</td>
					<?php endif; ?>
			<?php endforeach; ?>	
			</tr>
<?php endfor; ?>
	</table>
</div>
<div id="dialog-confirm"></div>

<script>
	// table
	$(function() {
		$('.table-hover td').unbind().click(function() {
			var Key = $(this).attr("data-key");
			var dataDisplay = $(this).attr("data-display");
			var reservable = $(this).attr("data-reservable");
			if (reservable !== "false") {
				if (confirm('<?php echo $this -> translate( 'Confirm reservation' ); ?>' + ':' + dataDisplay)) {
					jQuery.get('/ReservePianoRoom/m/' + Key, function(data) {
						if (data === "Success") {
							$(this).attr("data-reservable","false");
							Reload();
						} else if (data === "Exceed") {
							alert('Personal reserve limit exceed!');
						} else {
							alert('Something Wrong! ...' + data);
						}
					});
				}
			} else if($(this).attr("data-self") === "true"){
				if (confirm('<?php echo $this -> translate( 'Cancel reservation' ); ?>' + ':' + dataDisplay)) {
					jQuery.get('/ReservePianoRoom/m/' + Key + 'm/cancel/', function(data) {
						if (data === "Success") {
							$(this).attr("data-reservable","true");
							$(this).attr("data-self","false");
							Reload();
						} else {
							alert('Something Wrong! ...' + data);
						}
					});
				}
			} 
			return false;
		}).mouseover(function() {
			var reservable = $(this).attr("data-reservable");
			var self = $(this).attr("data-self");
			if (reservable === "true" || self === "true") {
				$(this).find('span').fadeIn(0);
				$(this).find('div').fadeOut(0);
			}
			return false;
		}).mouseout(function() {
			$(this).find('span').fadeOut(0);
			$(this).find('div').fadeIn(0);
			return false;
		});
	});

</script>

<style>
	.h3{
		color: #BFBFBF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);		
	}
	.table-content{
		color: #9F9F9F;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}
	.table-content-light{
		color: #FFFFFF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}	
	.table-content-another{
		color: #9999FF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}	
	.table-content-self{
		color: #9999FF;
		text-shadow: 0px 0px 4px rgba(0%,0%,0%,0.5);	
	}
</style>


<?php

function generateDateStrings( $first, $last, $format ) {
	$dateStrings = array();
	for ( $date = clone $first; $date <= $last; $date -> modify( '+1 day' ) ) {
		array_push( $dateStrings, $date -> format( $format ) );
	}
	return $dateStrings;
}

function weekDescription( $page, $first, $last, $view ) {
	if ( $page == 0 ) {
		return $view -> translate( 'Current Week' );
	} elseif ( $page == 1 ) {
		return $view -> translate( 'Next Week' );
	} elseif ( $page == -1 ) {
		return $view -> translate( 'Last Week' );
	} else {
		return $first -> format( 'Y-m-d' ) . '~' . $last -> format( 'Y-m-d' );
	}
}

function processData( $resultset, $room, $view ) {
	$current = $resultset -> current();
	$RecordItems = array();
	while ( $current ) {
		if ( $current -> room == $room || $current -> uid == $view -> zfcUserIdentity() -> getId() ) {
			if ( !array_key_exists( $current -> date, $RecordItems ) ) {
				$RecordItems[ $current -> date ] = array();
			}
			if ( !array_key_exists( $current -> class, $RecordItems[ $current -> date ] ) ) {
				$RecordItems[ $current -> date ][ $current -> class ] = array();
			}
			$RecordItems[ $current -> date ][ $current -> class ][ $current -> room ] = array(
				'reserve_id' => $current -> reserve_id,
				'room' => $current -> room,
				'uid' => $current -> uid,
				'displayName' => $current -> userData -> getDisplayName(),
				'flag' => $current -> flag,
				'comment' => $current -> comment,
			);
			$RecordItems[ $current -> date ][ $current -> class ][ 'room' ] = $current -> room;
		}
		$resultset -> next();
		$current = $resultset -> current();
	}
	return $RecordItems;
}

function getClassTime( $class ) {
	return sprintf( '%02d:00 ~ %02d:00', $class + 8, $class + 9 );
}

function getRoomText( $room, $view ) {
	switch ($room){
		case 1: return $view -> translate('Room 1');
		case 2: return $view -> translate('Room 2');
		case 3: return $view -> translate('Room 3');
	}
}
