<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %s NCKU Piano Club %s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate(' ')); ?></p>
    <!--
	<p><a class="btn btn-success btn-lg" href="https://github.com/Eddy0402/NCKUPianoClub" target="_blank"><?php echo $this->translate('GitHub') ?> &raquo;</a></p>
	-->
</div>

<div class="row-fluid">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Activity') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate(' ')); ?></p>
			</div>
        </div>
    </div>
			
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Recent Activity') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate(' ')); ?></p>
        </div>
    </div>
</div>
