
<div class="jumbotron" style="background-image: url(img/jumbotron_bg.jpg); background-size: 100%;">
	<div class="container">
		<h1><?php echo sprintf( $this -> translate( 'NCKU Piano Club' ), '', '' ) ?></h1>
		<p>　</p><p>　</p><p>　</p><p>　</p>
		<!-- 
		<p><a class="btn btn-success btn-lg" href="https://github.com/Eddy0402/NCKUPianoClub" target="_blank"><?php echo $this -> translate( 'GitHub' ) ?> &raquo;</a></p>
		-->
	</div>	
</div>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container text-center">
	<div class="row">
        <div class="col-lg-4 index-col">
            <i class="fa fa-calendar" style="font-size: 9em;"></i>
            <h2><?php echo $this->translate('Activity') ?></h2>
            <p><?php echo $this->translate('Activity description')?></p>
            <p>
                <div class="text-center" style="position:absolute; bottom: -30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                    <a href="<?php echo $this -> url( 'activity' ) ?>" class="btn btn-default">
                        <?php echo $this->translate('Go') ?> »
                    </a>
                </div>
            </p>
        </div>
        <div class="col-lg-4 index-col">
            <!--<img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="position: absolute; width: 140px; height: 140px;">-->
            <i class="fa fa-facebook-square" style="font-size: 9em;"></i>
            <h2><?php echo $this->translate('Facebook club') ?></h2>
            <p><?php echo $this->translate('Join Our Facebook Club...')?></p>
            <p>
                <div class="text-center" style="position:absolute; bottom: -30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                    <a href="https://www.facebook.com/groups/nckupiano/" class="btn btn-default" target="new">
                        <?php echo $this->translate('Go') ?> »
                    </a>
                </div>
            </p>
        </div>
        <div class="col-lg-4 index-col">
            <i class="fa fa-music" style="font-size: 9em;"></i>
            <h2><?php echo $this->translate('ReservePianoRoom') ?></h2>
            <p><?php echo $this->translate('Reserve Piano Room description')?></p>
            <p>
                <div class="text-center" style="position:absolute; bottom: -30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                    <a href="<?php echo $this -> url( 'ReservePianoRoom' ) ?>" class="btn btn-default">
                        <?php echo $this->translate('Go') ?> »
                    </a>
                </div>
            </p>
        </div>
      </div>
</div>	

<script>
function equalHeight(group) {    
    tallest = 0;    
    group.each(function() {       
        thisHeight = $(this).height();       
        if(thisHeight > tallest) {          
            tallest = thisHeight;       
        }    
    });    
    group.each(function() { $(this).height(tallest); });
} 

$(document).ready(function() {   
    equalHeight($(".index-col")); 
});
</script>