<?php
$form = $this->changeEmailForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal');
$form->setAttribute('role','form');
?>

<h1 class="text-center"><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h1>
<div class="col-lg-1"></div>
<div class="main-text col-lg-10">

<?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element): ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="form-group">		
                <div class="col-sm-12 btn">
                <?php $element -> setAttribute('class', 'btn btn-default'); ?>
                <?php echo $this->formButton($element) ?>
                </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div class="form-group">
                <?php if ($element->getLabel() != null): ?>
                <?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
                <?php echo $this->formLabel($element) ?>
                <?php else:?>
                <div class="col-sm-2"></div>
                <?php endif;?>
                <div class="col-sm-10">		
                    <?php $element -> setAttribute('class','form-control'); ?>
                    <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
                </div>
            </div>
        <?php else: ?>
            <div class="form-group">
                <?php if ($element->getLabel() != null): ?>
                <?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
                <?php echo $this->formLabel($element) ?>
                <?php else:?>
                <div class="col-sm-2"></div>
                <?php endif;?>
                <div class="col-sm-10">
                    <?php $element -> setAttribute('class','form-control'); ?>
                    <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
                </div>
            </div>
        <?php endif ?>
    <?php endforeach ?>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">        
            <input type="submit" value="Submit" class="btn btn-default"/>
        </div>
    </div>
<?php echo $this->form()->closeTag() ?>

<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
<?php endif; ?>

</div>
<div class=" col-lg-1"></div>