<?php
$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal');
$form->setAttribute('role','form');
?>

<h1 class="text-center"><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h1>
<div class="col-lg-1"></div>
<div class="main-text col-lg-10">
    
<?php echo $this->form()->openTag($form);?>

    <?php echo $this->formElementErrors($form->get('identity')); ?>
    <?php echo $this->formInput($form->get('identity')); ?>
    
    <div class="form-group">
        <?php $form->get('credential') -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
        <?php echo $this->formLabel($form->get('credential')); ?>  
        <div class="col-sm-10">
            <div class="thumbnail" style="margin-bottom:0px;">
                <?php $form->get('credential') -> setAttribute('class','form-control'); ?>
                <?php echo  $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?>
            </div>
        </div>
    </div>    
        
    <div class="form-group">
        <?php $form->get('newCredential') -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
        <?php echo $this->formLabel($form->get('newCredential')); ?>  
        <div class="col-sm-10">
            <div class="thumbnail" style="margin-bottom:0px;">
                <?php $form->get('newCredential') -> setAttribute('class','form-control'); ?>
                <?php echo  $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?>
            </div>
        </div>
    </div>    
        
    <div class="form-group">
        <?php $form->get('newCredentialVerify') -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
        <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>  
        <div class="col-sm-10">
            <div class="thumbnail" style="margin-bottom:0px;">
                <?php $form->get('newCredentialVerify') -> setAttribute('class','form-control'); ?>
                <?php echo  $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')); ?>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">     
            <?php $form->get('submit') -> setAttribute('class','btn btn-default'); ?>
            <?php echo $this->formInput($form->get('submit'));?>
        </div>
    </div>

<?php echo $this->form()->closeTag(); ?>

<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>

</div>
<div class=" col-lg-1"></div>