<?php $user = $this -> zfcUserIdentity(); ?>

<div class="container">
    <div class="col-lg-1"></div>
    <div class="main-text col-lg-10">

        <p></p>
        
        <div class="container">
        <div style="float:left; padding-right:16px;">
            <?php echo $this -> gravatar( $user -> getEmail() ) ?>
        </div>
        <h3>
            <?php echo $this -> translate( 'Welcome back' ); ?>, <?php echo $this -> zfcUserDisplayName(); ?>
        </h3>
        <a href="<?php echo $this -> url( 'zfcuser/logout' ) ?>" class="btn-sm btn-default">
            <?php echo $this -> translate( 'Sign Out' ); ?>
        </a>
        </div>
        
        <p></p>
        
        <div class="panel panel-default">
            <table class="table">
                <tr>
                    <td><?php echo $this->translate('Display Name');?></td>
                    <td><?php echo $user->getDisplayName()?></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Email');?></td>
                    <td><?php echo $user->getEmail()?></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Card Id');?></td>
                    <td><?php echo $user->getCardId()?></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Role');?></td>
                    <td>
                        <?php switch ($user->getRole()){
                            case 0: echo $this->translate('Normal Member'); break;
                            case 1: echo $this->translate('Admin'); break;
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('State');?></td>
                    <td>
                        <?php switch ($user->getState()){
                            case 0: echo $this->translate('Not Activated'); break;
                            case 1: echo $this->translate('Site Password'); break;
                            case 2: echo $this->translate('NCKU Website'); break;
                        }
                        ?>
                    </td>
                </tr>
            </table>
        </div>

        <p></p>
        
        <div class="row">
            <div class="col-lg-4">
                <div class="thumbnail">
                    <img data-src="holder.hs/300x300" />
                    <div class="caption">                        
                        <h3 class="text-center"><?php echo $this -> translate( 'ReservePianoRoom' ) ?></h3>
                        <p> <?php echo $this->translate('Reserve the piano room for next week, see which room is available this week.')?> </p>
                    </div>
                    <div class="text-center" style="position:absolute; bottom: 30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                        <a href="<?php echo $this -> url( 'ReservePianoRoom' ) ?>" class="btn btn-default">
                            <?php echo $this->translate('Enter')?>
                        </a>
                    </div>
                </div>
                
            </div>
            
            <div class="col-lg-4">
                <div class="thumbnail">
                    <img data-src="holder.hs/300x300" />
                    <div class="caption" style="padding-bottom: 40px;">                        
                        <h3 class="text-center"><?php echo $this -> translate( 'Change Password' ) ?></h3>
                        <p> <?php echo $this->translate('Change password that stored in this site, if the password is link to NCKU, change it at NCKU website instead.')?> </p>
                    </div>
                    <div class="text-center" style="position:absolute; bottom: 30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                        <a href="<?php echo $this -> url( 'zfcuser/changepassword' ) ?>" class="btn btn-default">
                            <?php echo $this->translate('Enter')?>
                        </a>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <div class="thumbnail">
                    <img data-src="holder.hs/300x300" />
                    <div class="caption">                        
                        <h3 class="text-center"><?php echo $this -> translate( 'Change Email' ) ?></h3>
                        <p> <?php echo $this->translate('The email field in this site has no affect at this time, We may have new feed in future.')?> </p>
                    </div>
                    <div class="text-center" style="position:absolute; bottom: 30px;left:0;right:0;margin-left:auto;margin-right:auto;">
                        <a href="<?php echo $this -> url( 'zfcuser/changeemail' ) ?>" class="btn btn-default">
                            <?php echo $this->translate('Enter')?>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class=" col-lg-1"></div>
</div>

<script>
function equalHeight(group) {    
    tallest = 0;    
    group.each(function() {       
        thisHeight = $(this).height();       
        if(thisHeight > tallest) {          
            tallest = thisHeight;       
        }    
    });    
    group.each(function() { $(this).height(tallest); });
} 

$(document).ready(function() {   
    equalHeight($(".thumbnail")); 
});
</script>