

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal');
$form->setAttribute('role','form');
?>

<h1 class="text-center"><?php echo $this->translate('Sign In'); ?></h1>
<div class="col-lg-1"></div>
<div class="main-text col-lg-10">

<?php echo $this->form()->openTag($form) ?>

        <?php echo $this->formElementErrors($form->get('identity')) ?>
        
        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate('Username')?></label>   
            <div class="col-sm-10">
                <div class="thumbnail" style="margin-bottom:0px;">
                    <?php $form->get('identity') -> setAttribute('class','form-control'); ?>
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <?php $form->get('credential') -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
            <?php echo $this->formLabel($form->get('credential')) ?>       
            <div class="col-sm-10">
                <div class="thumbnail" style="margin-bottom:0px;">
                    <?php $form->get('credential') -> setAttribute('class','form-control'); ?>
                    <?php echo $this->formInput($form->get('credential')) ?>
                </div>
            </div>
        </div>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <div class="form-group "> 
            <div class="col-sm-10 col-sm-offset-2">
                <?php $form->get('submit') -> setAttribute('class', 'btn btn-default'); ?>
                <?php echo $this->formButton($form->get('submit')) ?>
            </div>
        </div>

<?php echo $this->form()->closeTag() ?>

<div class="text-muted text-center">
<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
</div>

</div>
<div class=" col-lg-1"></div>