<?php

if (!$this->enableRegistration) {
    echo $this->translate('Registration is disabled');
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal');
$form->setAttribute('role','form');
?>

<div class="container">
<div class="col-lg-1"></div>
<div class="main-text col-lg-10">


<h1 class="text-info text-center"><?php echo $this->translate('Register'); ?></h1>


<?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element): ?>				
			<?php if ($element instanceof Zend\Form\Element\Button): ?>
				<div class="form-group">		
					<div class="col-sm-12 btn">
					<?php $element -> setAttribute('class', 'btn btn-default'); ?>
					<?php echo $this->formButton($element) ?>
					</div>
				</div>
			<?php elseif ($element ->  getAttribute('type') == 'password'): ?>
				<div class="form-group">
					<?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
					<?php echo $this->formLabel($element) ?>
					<div class="col-sm-10">
						<?php $element -> setAttribute('class','form-control'); ?>
						<?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
                        <span class="help-block">
                            <?php echo $this->translate('If you use NCKU\'s password, this account wiil be automatically connect to NCKU\'s database.')?>
                        </span>
					</div>
				</div>
			<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
				<div class="form-group">
					<?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
					<?php echo $this->formLabel($element) ?>
					<div class="col-sm-10">		
						<?php $element -> setAttribute('class','form-control'); ?>
						<?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
					</div>
				</div>
			<?php elseif ($element instanceof Zend\Form\Element\Radio): ?>
				<div class="form-group">
					<?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
					<?php echo $this->formLabel($element) ?>
					<div class="col-sm-10">		
						<?php $element -> setAttribute('class','form-control'); ?>
						<?php echo $this -> formRadio($element);  ?>
					</div>
				</div>
			<?php else: ?>
				<div class="form-group">
					<?php $element -> setLabelAttributes(array('class'=>'col-sm-2 control-label')); ?>
					<?php echo $this->formLabel($element) ?>
					<div class="col-sm-10">
						<?php $element -> setAttribute('class','form-control'); ?>
						<?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
					</div>
				</div>
			<?php endif ?>
    <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

		
</div>
<div class=" col-lg-1"></div>
</div>