<?php $this->headTitle( $post->title) ?>

<div class="container">
	<div class="main-text col-lg-10 col-lg-offset-1">
		<h1 class="text-center"> <?=$post->title;?></h1>
		<div class="text-muted text-center"> By <?=$post->uid?> | <?= $post->time?></div>
		<div class="divider"></div>
		<?=$this->markdown( $post->content )?>
		<div class="divider"></div>
		<?=$post->url?>
	</div>
	<div class="col-lg-10 col-lg-offset-1">
		<div id="disqus_thread"></div>
	</div>
</div>
<script type="text/javascript">
	/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	var disqus_shortname = 'ncku-piano'; // required: replace example with your forum shortname
	var disqus_developer = 1;
	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function() {
		var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

