<?php $this->headTitle( $post->title) ?>

<div>
	<div class="row">
		<div class="main-text col-lg-10 col-lg-offset-1">
			<h1 class="text-center"> <?=$post->title;?></h1>
			<div class="text-muted text-center"> By <?=$post->uid?> | <?= $post->time?></div>
			<hr class="divider" />
			<?=$this->markdown( $this->escapeHTML($post->content) )?>
			<hr class="divider" />
            <?php if($this->zfcUserIdentity() && $this->zfcUserIdentity()->getRole() == 1): ?>
                <a class="btn btn-default" href="<?php echo $this->url('activity/edit',array('article'=>$post->url)); ?>">
                    Edit
                </a>
            <?php endif;?>
		</div>
	</div>
	<hr class="divider" />
	<div class="row">
		<div class=" col-lg-10 col-lg-offset-1" style="bottom: 30px; padding-top: 30px;">
			<a href="http://disqus.com" class="dsq-brlink text-muted text-center">
				comments powered by <span class="logo-disqus">Disqus</span>
			</a>
			<div id="disqus_thread"></div>
		</div>
	</div>
</div>

<script type="text/javascript">
	/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	var disqus_shortname = 'ncku-piano'; // required: replace example with your forum shortname
	var disqus_developer = 1;
	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function() {
		var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
