<?php 
    $this->headTitle($this->translate('Acticity'));
?>
<?php if($this->zfcUserIdentity() && $this->zfcUserIdentity()->getRole() == 1): ?>
<div class="container" style="padding-top: 10px;">
    <p>
        <a class="btn btn-default" href="<?php echo $this->url('activity/post'); ?>">
        New Post
        </a>
    </p>
</div>
<?php endif;?>
<div class="container">
    <div class="col-lg-9" role="main">
        <?php while($post = $this->dataSet->current()): ?>
            <p style="margin-bottom: 60px;" id="<?=$post->id;?>">
                <h2><?=$post->title;?></h2>
                <hr class="divider">
                
                <blockquote><?=$this->markdown( $this->escapeHTML($post->summary) )?></blockquote>
                
                <div class="text-muted text-right">
                    <a href="activity/article/<?=$post->url?>"><?php echo $this->translate('Read More...');?></a>
                    By <?=$post->uid?> | <?= $post->time?>
                </div>
            </p>

        <?php $dataSet->next();?>
        <?php endwhile;?>
        <div class="text-center">
            <ul class="pagination">
                <li class="<?php if($page - 1 == 0):?>disabled<?php endif;?>">
                    <a href="<?php echo $this->url('activity/page',array('page'=>$page - 1))?>">&laquo;</a>
                </li>
                <?php $pagestart = ($this->page - 1) - ($this -> page - 1 ) % 10 + 1 ?>
                <?php $pageend = min(array($this-> pagecount,$pagestart + 9))?>
                <?php for($p = $pagestart ; $p <= $pageend; $p++):?>
                  <li class='<?=($page == $p ? 'active' :'')?>'>
                    <a href="<?php echo $this->url('activity/page',array('page'=>$p))?>">
                        <?php echo $p?>
                    </a>
                </li>
                <?php endfor;?>
                <li class="<?php if($page == $pagecount):?>disabled<?php endif;?>">
                    <a href="<?php echo $this->url('activity/page',array('page'=>$page + 1))?>">&raquo;</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3">
        <div style="position: fixed">
            <p>
                <h3><?php echo $this->translate('Jump to:')?></h3>
                <ul>
                <?php $this->dataSet->rewind(); ?>
                <?php while($post = $this->dataSet->current()): ?>
                    <li class="list-unstyled">
                        <span class="glyphicon glyphicon-tag"></span>
                        <a href="#<?=$post->id;?>"><?=$post->title;?></a>
                    </li>
                <?php $dataSet->next();?>
                <?php endwhile;?>
                </ul>
            </p>
            <p>
                <h3><?php echo $this->translate('Categories')?></h3>
                <ul>
                    <li class="list-unstyled">
                        <span class="glyphicon glyphicon-list"></span>
                        <a href="<?php echo $this->url('activity/category',array('category'=>'未分類文章'))?>">未分類文章</a>
                    </li>
                    <li class="list-unstyled">
                        <span class="glyphicon glyphicon-list"></span>
                        <a href="<?php echo $this->url('activity/category',array('category'=>'活動'))?>">活動</a>
                    </li>
                    <li class="list-unstyled">
                        <span class="glyphicon glyphicon-list"></span>
                        <a href="<?php echo $this->url('activity/category',array('category'=>'社課資訊'))?>">社課資訊</a>
                    </li>
                </ul>
            </p>
            
        </div>
    </div>
</div>

<!---->