<?php
	$current = $resultset->current();
	
	$dateStrings = array();
	for ( $date = clone $first; $date <= $last ;$date->modify('+1 day') ){
		array_push($dateStrings, $date -> format('Y-m-d'));
	}
	
	$RecordItems = array();
	while($current){
		if(!array_key_exists($current->date,$RecordItems)){
			$RecordItems[$current->date] = array();
		}
		if(!array_key_exists($current->class,$RecordItems[$current->date])){
			$RecordItems[$current->date][$current->class] = array();
		}
		$RecordItems[$current->date][$current->class][$current->room] = array(
			'reserve_id' => $current->reserve_id,
			'room' => $current->room,
			'uid' => $current->uid,
			//'username' => $current->username,
			'flag' => $current->flag,
			'comment' => $current-> comment,
		);
		
		$resultset->next();
		$current = $resultset->current();		
	}
	
	
?>		

<div class="table-responsive" style="margin-top: -20px;">	
		<?php if($page == 0):?>
			<?php echo $this->translate('Current Week'); ?>
		<?php elseif($page == 1):?>
			<?php echo $this->translate('Next Week'); ?>
		<?php elseif($page == -1):?>
			<?php echo $this->translate('Last Week'); ?>
		<?php else:?>
			<?php echo $first -> format('Y-m-d'). '~' . $last -> format('Y-m-d');?>
		<?php endif;?>
	<table class="table table-striped table-hover">
		<tbody>
		<tr>
			<th class="text-center"><?php echo $this->translate('Time \\ Date');?></th>
			<?php for ( $date = clone $first; $date <= $last ;$date->modify('+1 day') ) : ?>
			<th class="text-center">
				<?php echo $date -> format('m-d'); ?>
			</th>
			<?php endfor;?>
		</tr>

		<?php for( $class = 0; $class < 14; $class++ ): ?>
			<tr>
				<th class="text-center"><?php echo sprintf('%02d:00 ~ %02d:00',$class+8,$class+9) ?></th>
				<?php for ( $date = clone $first; $date <= $last ;$date->modify('+1 day') ) : ?>
				<?php $dateString = $date -> format('Y-m-d'); ?>

				<?php if( array_key_exists($dateString,$RecordItems) && array_key_exists($class,$RecordItems[$dateString])): ?>
					<td class="text-center" data-key="" data-isReserved="true">
						<?php foreach($RecordItems[$dateString][$class] as $record): ?>
							<span class="glyphicon glyphicon-remove-sign"></span>
						<?php endforeach;?>
					</td>
				<?php else: ?>
					<td class="text-center" data-key="" data-isReserved="false">
						reserve
					</td>
				<?php endif;?>
				

				<?php endfor; ?>	
			</tr>
		<?php endfor; ?>
		</tbody>
	</table>
</div>
<div id="dialog-confirm"></div>
<script language="script/jacascript">
	$(function() {
        $('.table-hover td').unbind().click(function() {
            var Key = $(this).attr("data-key");
			var isReserved = $(this).attr("data-isReserved");
			if( isReserved === "true" ){
				if(confirm("T")){
					
				}
			}else {
				if(confirm("F")){
					
				}
			}
        });
	});

</script>
