<?php echo $this -> doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
		<?php echo $this -> headTitle( $this -> translate( 'NCKU Piano Club' ) ) -> setSeparator( ' - ' ) -> setAutoEscape( false ) ?>

		<?php
		echo $this -> headMeta()
			-> appendName( 'viewport', 'width=device-width, initial-scale=1.0' )
			-> appendHttpEquiv( 'X-UA-Compatible', 'IE=edge' )
		?>
		<meta name="google-site-verification" content="9g9rPTix_tIN2mEcbqSFMR38GQJi2hJa0D6PJqzUuYc" />

        <!-- Le styles -->
		<?php
		echo $this -> headLink( array( 'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this -> basePath() . '/img/favicon.ico' ) )
			-> prependStylesheet( $this -> basePath() . '/css/bootstrap.min.css' )
		?>

        <!-- Scripts -->
		<?php
		echo $this -> headScript()
			-> prependFile( $this -> basePath() . '/js/bootstrap.min.js' )
			-> prependFile( $this -> basePath() . '/js/jquery.min.js' )
			-> prependFile( $this -> basePath() . '/js/respond.min.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) )
			-> prependFile( $this -> basePath() . '/js/html5shiv.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) )
		;
		?>
		<style type="text/css">

			  /* Sticky footer styles
			  -------------------------------------------------- */
			  html,
			  body {
				height: 100%;
				/* The html and body elements cannot have any padding or margin. */
			  }

			  /* Wrapper for page content to push down footer */
			  #wrap {
				min-height: 100%;
				height: auto !important;
				height: 100%;
				/* Negative indent footer by it's height */
				margin: 0 auto -30px;
			  }

			  /* Set the fixed height of the footer here */
			  #push,
			  #footer {
				height: 30px;
			  }
			  #footer {
				background-color: #f5f5f5;
			  }

			  /* Lastly, apply responsive CSS fixes as necessary */
			  @media (max-width: 767px) {
				#footer {
				  margin-left: -20px;
				  margin-right: -20px;
				  padding-left: 20px;
				  padding-right: 20px;
				}
			  }

			  /* Custom page CSS
			  -------------------------------------------------- */
			  /* Not required for template or sticky footer method. */

			  #wrap > .content {
				padding-top: 51px;
				min-height: 100%;
				height: 100%;
			  }

		</style>
    </head>
    <body>
		<div id="wrap">
			<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
                        <a class="navbar-brand" href="<?php echo $this -> url( 'home' ) ?>"><img src="<?php echo $this -> basePath( 'img/zf2-logo.png' ) ?>" style="width: 10px; height: 20px;" alt="Zend Framework 2"/>&nbsp;<?php echo $this -> translate( 'Piano Club' ) ?></a>
					</div>

					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
							<li><a href="<?php echo $this -> url( 'activity' ) ?>"><?php echo $this -> translate( 'Activity' ) ?></a></li>
							<li><a href="<?php echo $this -> url( 'about' ) ?>"><?php echo $this -> translate( 'Overview' ) ?></a></li>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<?php if(! $this->zfcUserIdentity()): ?>
								<li><a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a></li>
							<?php endif?>
							<li class="dropdown navbar-right">	
								<?php if(! $this->zfcUserIdentity()): ?>						
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										<span class="glyphicon glyphicon-log-in"> 
										<?php echo $this -> translate( 'Login' ) ?> 
										<!--<span class="glyphicon glyphicon-chevron-down"></span>-->
									</a>

									<?php echo $this->zfcUserLoginWidget(array('redirect'=>'home')); ?>

								<?php else: ?>
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 9px; padding-bottom: 9px;">
										<?php
											echo $avatar = $this->gravatar($this->zfcUserIdentity()->getEmail(),
												array(),
												array('width'=>'32px','height'=>'32px'));
										?>
										<?php echo $this->zfcUserIdentity()->getDisplayname(); ?>　
										<span class="glyphicon glyphicon-chevron-down"></span>
									</a>
									<ul class="dropdown-menu" role="menu">
										<li><a href="<?php echo $this -> url( 'zfcuser' );?>"> <?php echo $this->translate('Profile'); ?></a></li>
										<li><a href="<?php echo $this->url('ReservePianoRoom');?>"> <?php echo $this->translate('Piano Room'); ?></a></li>
										<li class="hidden"><a href=""> <?php echo $this->translate('Sheet Music'); ?></a></li>
										<li class="divider"></li>
										<li><a href="<?php echo $this -> url( 'zfcuser/changepassword' );?>"> <?php echo $this->translate('Settings'); ?></a></li>
										<li><a href="<?php echo $this->url('zfcuser/logout') ?>"> <?php echo $this->translate('Logout'); ?></a></li>
									</ul>
								<?php endif ?>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="content">
				<?php echo $this -> content; ?>	
			</div>
			<div id="push"></div>
		</div>
		<div id="footer">
			<div class="text-muted text-center">
				<p>&copy; <?php echo date( 'Y' ) ?> <?php echo $this -> translate( 'NCKU Piano Club' ) ?></p>
			</div>
		</div>
<?php echo $this -> inlineScript() ?>
    </body>
</html>
