<?php echo $this -> doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
		<?php echo $this -> headTitle( $this -> translate( 'NCKU Piano Club' ) ) -> setSeparator( ' - ' ) -> setAutoEscape( false ) ?>

		<?php
		echo $this -> headMeta()
			-> appendName( 'viewport', 'width=device-width, initial-scale=1.0' )
			-> appendHttpEquiv( 'X-UA-Compatible', 'IE=edge' )
		?>

        <!-- Le styles -->
		<?php
		echo $this -> headLink( array( 'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this -> basePath() . '/img/favicon.ico' ) )
			-> prependStylesheet( $this -> basePath() . '/css/style.css' )
			-> prependStylesheet( $this -> basePath() . '/css/bootstrap-theme.min.css' )
			-> prependStylesheet( $this -> basePath() . '/css/bootstrap.min.css' )
		?>

        <!-- Scripts -->
		<?php
		echo $this -> headScript()
			-> prependFile( $this -> basePath() . '/js/bootstrap.min.js' )
			-> prependFile( $this -> basePath() . '/js/jquery.min.js' )
			-> prependFile( $this -> basePath() . '/js/respond.min.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) )
			-> prependFile( $this -> basePath() . '/js/html5shiv.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) )
		;
		?>
	
    </head>
    <body>
		<nav class="navbar navbar-static-top navbar-fixed-top navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header" style="padding:4px">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this -> url( 'home' ) ?>"><img src="<?php echo $this -> basePath( 'img/zf2-logo.png' ) ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this -> translate( 'Piano Club' ) ?></a>
				</div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" style="padding:4px">
                        <li><a href="<?php echo $this -> url( 'home' ) ?>"><?php echo $this -> translate( 'Activity' ) ?></a></li>
                        <li><a href="<?php echo $this -> url( 'activity' ) ?>"><?php echo $this -> translate( 'Overview' ) ?></a></li>
						<?php if(! $this->zfcUserIdentity()): ?>
							<li><a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a></li>
						<?php endif?>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown navbar-right">	
							<?php if(! $this->zfcUserIdentity()): ?>						
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<span class="glyphicon glyphicon-log-in"> 
									<?php echo $this -> translate( 'Login' ) ?> 
									<!--<span class="glyphicon glyphicon-chevron-down"></span>-->
								</a>
								
								<?php echo $this->zfcUserLoginWidget(array('redirect'=>'home')); ?>

							<?php else: ?>
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<!--
										<img src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xap1/t1.0-9/1380776_581815175213582_571785533_n.jpg"  class="img-circle" height="32px" width="32px"> 
									-->
									<?php
										echo $avatar = $this->gravatar($this->zfcUserIdentity()->getEmail(),
											array(),
											array('width'=>'32px','height'=>'32px'));
									?>
									<?php echo $this->zfcUserIdentity()->getDisplayname(); ?>　
									<span class="glyphicon glyphicon-chevron-down"></span>
								</a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="<?php echo $this -> url( 'zfcuser' );?>"> <?php echo $this->translate('Profile'); ?></a></li>
									<li><a href="<?php echo $this->url('ViewReserveTable');?>"> <?php echo $this->translate('Piano Room'); ?></a></li>
									<li class="hidden"><a href=""> <?php echo $this->translate('Sheet Music'); ?></a></li>
									<li class="divider"></li>
									<li><a href="<?php echo $this -> url( 'zfcuser/changepassword' );?>"> <?php echo $this->translate('Settings'); ?></a></li>
									<li><a href="<?php echo $this->url('zfcuser/logout') ?>"> <?php echo $this->translate('Logout'); ?></a></li>
								</ul>
							<?php endif ?>
						</li>
					</ul>
                </div>

            </div>
        </nav>        
		<?php echo $this -> content; ?>		
		<div class="footer ">
			<div class="container">
			  <p class="text-muted text-center">&copy; <?php echo date( 'Y' ) ?> <?php echo $this -> translate( 'NCKU Piano Club' ) ?></p>
			</div>
		</div>
<?php echo $this -> inlineScript() ?>
    </body>
</html>
