
<ul class="dropdown-menu" role="menu" style=" width: 250px;margin-left: auto;margin-right: auto;">
		
<li><h4 class="text-center"><?php echo $this->translate('Sign In'); ?></h4></li>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>

<?php echo $this->form()->openTag($form) ?>

<?php echo $this->formElementErrors($form->get('identity')) ?>
	<div class="input-group text-center">
        <input name="identity" type="text" placeholder="Username" class="form-control" style="margin-left: 5%;margin-right: 5%;margin-top: 5px; width: 90%;">
        <input name="credential" type="password" placeholder="Password" class="form-control" style="margin-left: 5%;margin-right: 5%;margin-top: 5px; width: 90%;">	
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-default" style="margin-top: 5px;margin-right: auto;margin-left: auto;">
            <?php echo $this->translate('Sign in'); ?>
        </button>
    </div>

	<?php //echo $this->formLabel($form->get('identity')) ?>
	<?php //echo $this->formInput($form->get('identity')) ?>
	<?php //echo $this->formLabel($form->get('credential')) ?>
	<?php //echo $this->formInput($form->get('credential')) ?>
	
	<?php if ($this->redirect): ?>
		<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
	<?php endif ?>

<?php echo $this->form()->closeTag() ?>

<?php //if ($this->enableRegistration) : ?>
<?php //endif; ?>

</ul>
