
<ul class="dropdown-menu" role="menu" style="padding: 10px; width: 200px;">
		
<li><h2 class="text-center"><?php echo $this->translate('Sign In'); ?></h2></li>


<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>

<?php echo $this->form()->openTag($form) ?>

<?php echo $this->formElementErrors($form->get('identity')) ?>
	
	<input name="identity" type="text" placeholder="Username" class="form-control" style="margin-top: 5px;">
	<input name="credential" type="password" placeholder="Password" class="form-control" style="margin-top: 5px;">	
	<button type="submit" class="btn btn-default pull-right"  style="margin-top: 5px;">
		<?php echo $this->translate('Sign in'); ?>
	</button>

	<?php //echo $this->formLabel($form->get('identity')) ?>
	<?php //echo $this->formInput($form->get('identity')) ?>
	<?php //echo $this->formLabel($form->get('credential')) ?>
	<?php //echo $this->formInput($form->get('credential')) ?>
	
	<?php if ($this->redirect): ?>
		<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
	<?php endif ?>

<?php echo $this->form()->closeTag() ?>

<?php //if ($this->enableRegistration) : ?>
<?php //endif; ?>

</ul>
